import type { Metadata } from "next";

import "./globals.css";
import Header from "./containers/Header";

export const metadata: Metadata = {
  title: "Manhattan My Way",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* put Header here */}
        <Header />
        {children}
        {/* put Footer here */}
      </body>
    </html>
  );
}
