# Pre-commit hooks configuration
# Install: pip install --user pre-commit
# Setup: bash scripts/setup-git-hooks.sh

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']  # 增加到 1MB，适应项目需求
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3
        files: ^ml/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^ml/.*\.py$
        args: [--max-line-length=88, --extend-ignore=E203,W503]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^webapp/.*\.(js|jsx|ts|tsx|json|css|md)$
        exclude: |
          (?x)^(
            webapp/node_modules/.*|
            webapp/\.next/.*|
            webapp/out/.*|
            webapp/dist/.*
          )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.0
    hooks:
      - id: eslint
        files: ^webapp/.*\.(js|jsx|ts|tsx)$
        additional_dependencies:
          - eslint@8.57.0
          - '@typescript-eslint/eslint-plugin@6.21.0'
          - '@typescript-eslint/parser@6.21.0'
          - '@next/eslint-config-next@14.0.0'
