version: '3.8'

services:
  webapp:
    build:
      context: ./webapp
    ports:
      - "3030:3000"
    volumes:
      - ./webapp:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      
