version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3030:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      
