# GitLab CI/CD Pipeline using GitLab Runner
# Designed for self-hosted GitLab Runner

stages:
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

# Deploy to staging (develop branch)
deploy_staging:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags:
    - docker
  before_script:
    - apk add --no-cache docker-compose git
    - docker info
  script:
    - echo "Building and deploying to staging..."
    - echo "Current directory:" && pwd
    - echo "Files:" && ls -la
    - docker-compose --version
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up -d
    - docker-compose ps
    - echo "Staging deployment completed!"
    - echo "Access at: http://137.43.49.26:3030"
  environment:
    name: staging
    url: http://137.43.49.26:3030
  only:
    - develop

# Deploy to production (main branch)
deploy_production:
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  tags:
    - docker
  before_script:
    - apk add --no-cache docker-compose git
    - docker info
  script:
    - echo "Building and deploying to production..."
    - echo "Current directory:" && pwd
    - echo "Files:" && ls -la
    - docker-compose --version
    - docker-compose -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.prod.yml up -d
    - docker-compose -f docker-compose.prod.yml ps
    - echo "Production deployment completed!"
    - echo "Access at: http://137.43.49.26:8080"
  environment:
    name: production
    url: http://137.43.49.26:8080
  only:
    - main
  when: manual
