import type { Metadata } from "next";

import "./globals.css";

import Header from "./containers/Header";
import AuthWrapper from "./containers/AuthWrapper";

export const metadata: Metadata = {
  title: "Manhattan My Way",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthWrapper>
          <main className="min-h-dvh flex flex-col">
          {/* put Header here */}
          <Header />
          {children}
          {/* put Footer here */}
          </main>
        </AuthWrapper>
      </body>
    </html>
  );
}
